liip_imagine:
    # configure webp
    # webp:
    #     generate: true

    # example filter
    # filter_sets:
    #     thumbnail_web_path:
    #         filters:
    #             thumbnail: { size: [223, 223], mode: inset }  
  filter_sets:
    thumb:
      quality: 75
      filters:
        thumbnail:
          size:          [150, 150]
          mode:          outbound
    
    medium:
      quality: 75
      filters:
        thumbnail:
          size:          [300, 230]
          mode:          outbound
   
    large:
      quality: 75
      filters:
        thumbnail:
          size:          [1200, 350]
          mode:          outbound
