liip_imagine:
    # configure webp
    # webp:
    #     generate: true

    # example filter
    # filter_sets:
    #     thumbnail_web_path:
    #         filters:
    #             thumbnail: { size: [223, 223], mode: inset }  
  filter_sets:
    thumb:
      quality: 75
      filters:
        thumbnail:
          size:          [360, 230]
          mode:          outbound
    medium:
      quality: 75
      filters:
        thumbnail:
          size:          [800, 530]
          mode:          outbound