vich_uploader:
    db_driver: orm 

    mappings:
       post_image:
           uri_prefix: /media
           upload_destination: '%kernel.project_dir%/public/media'
           namer: Vich\UploaderBundle\Naming\UniqidNamer

       joueur_image:
           uri_prefix: /images/joueurs
           upload_destination: '%kernel.project_dir%/public/images/joueurs'
           namer: Vich\UploaderBundle\Naming\UniqidNamer

